- hosts: harvester
  gather_facts: no

  tasks:
  - name: install pip
    become: yes
    apt:
      name: python-pip
      state: present

  - name: install virtualenv
    become: yes
    pip:
      name: virtualenv

  - name: copy private key for GitHub access
    copy:
      src: /mnt/d/GDrive/Docs/2017/Code/amost-twitter-analytics/auto-deploy/ansible/files/git.pem
      dest: ~/.ssh/id_rsa
      owner: ubuntu
      group: ubuntu
      mode: 0700
  
  - name: clone harvester git repo
    git:
      repo: git@github.com:martindavid/amost-twitter-analytics.git
      dest: /home/ubuntu/amost-twitter-analytics
      accept_hostkey: yes

  - name: install harvester requirements
    become: yes
    pip:
      requirements: /home/ubuntu/amost-twitter-analytics/twitter-harvester/requirements.txt

  - name: copy env file for harvester
    copy:
      src: /mnt/d/GDrive/Docs/2017/Code/amost-twitter-analytics/auto-deploy/ansible/files/.env
      dest: ~/amost-twitter-analytics/twitter-harvester
      owner: ubuntu
      group: ubuntu
      mode: 0700
  
  - name: setup PostgreSQL DB with keywords & tokens
    shell: "{{item}}"
    args:
      chdir: ~/amost-twitter-analytics/twitter-harvester
    with_items:
      - sudo -u postgres psql -f db_structure/create.sql amost_twitter
      - sudo -u postgres psql -f db_structure/keyword.sql amost_twitter
      - sudo -u postgres psql -f db_structure/twitter_token.sql amost_twitter

  - name: start harvester [G1]
    shell: nohup python ~/amost-twitter-analytics/twitter-harvester/cli.py stream GROUP1 &
